---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.5.0
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-6 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.3
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    services: docker
    sudo: required
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "lBcc0WYIK5ZETsNeS2jlc71o1RXiM96tvLG7TVv4WB/fTrntcQQ8bKHTAmtY2rHhi9w+KSyPqTJFqKcI/xTxJ6iIqTINoRLnEznfUclAoyYdxrkjT74UyZTf+dw1jiqLhqd6DIbQFHZ5WXob/ta8bnw5qwS9uw/tOzPJKRFXfcw="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
